[package]
name = "data-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.8.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "macros", "migrate", "rust_decimal"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "cookies", "native-tls"] }
chrono = { version = "0.4", features = ["serde"] }
yfinance-rs = "0.8.0"
rust_decimal = "1.42.0"
rand = "0.8"