name: Data Collector Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_data_collector_user
          POSTGRES_PASSWORD: test_data_collector_password
          POSTGRES_DB: test_db_dc
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_data_collector_user -d test_db_dc"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Protoc (yfinance)
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features rustls,postgres

      - name: Run Project Tests
        env:
          DATABASE_URL: postgres://test_data_collector_user:test_data_collector_password@localhost:5432/test_db_dc
        run: |
          cargo sqlx migrate run
          cargo test